apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebappp 
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: samplewebappp
  template:
    metadata:
      labels:
        app: samplewebappp
    spec:
      containers:
        - name: sampleapp 
          image: rishikaregistry.azurecr.io/samplewebappp
          ports:
          - containerPort: 80
